程序出现异常
异常说明：System.Type--
2018-06-04 09:12:32
★异常类型：ArgumentOutOfRangeException
★异常消息：指定的参数已超出有效值的范围。
参数名: offset
★异常信息：   在 System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   在 udp_csharp.BufferManager.SetBuffer(SocketAsyncEventArgs args) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\BufferManager.cs:行号 58
   在 udp_csharp.BufferManager.SetBufferValue(SocketAsyncEventArgs args, Byte[] content) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\BufferManager.cs:行号 66
   在 udp_csharp.UdpSendSocket.Send(Byte[] content, EndPoint remoteEndPoint) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpSendSocket.cs:行号 88
   在 udp_csharp.UdpServer.Send(Byte[] content, EndPoint remoteEndPoint) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpServer.cs:行号 84
   在 CleanProcedure.CleanManager.ProcessDelegate(QueueInfo info) 位置 f:\GitHub\CleanProcedure\Decontamination\CleanManager.cs:行号 67
   在 audiotest.BusinessInfoHelper.ScanQueue() 位置 f:\GitHub\CleanProcedure\CleanProcedure\comm\smessagequeue.cs:行号 91



程序出现异常
异常说明：System.Type--
2018-06-04 09:13:24
★异常类型：ArgumentOutOfRangeException
★异常消息：指定的参数已超出有效值的范围。
参数名: offset
★异常信息：   在 System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   在 udp_csharp.BufferManager.SetBuffer(SocketAsyncEventArgs args) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\BufferManager.cs:行号 58
   在 udp_csharp.BufferManager.SetBufferValue(SocketAsyncEventArgs args, Byte[] content) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\BufferManager.cs:行号 66
   在 udp_csharp.UdpSendSocket.Send(Byte[] content, EndPoint remoteEndPoint) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpSendSocket.cs:行号 88
   在 udp_csharp.UdpServer.Send(Byte[] content, EndPoint remoteEndPoint) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpServer.cs:行号 84
   在 CleanProcedure.CleanManager.ProcessDelegate(QueueInfo info) 位置 f:\GitHub\CleanProcedure\Decontamination\CleanManager.cs:行号 67
   在 audiotest.BusinessInfoHelper.ScanQueue() 位置 f:\GitHub\CleanProcedure\CleanProcedure\comm\smessagequeue.cs:行号 91



程序出现异常
异常说明：System.Type--
2018-06-04 11:03:04
★异常类型：InvalidOperationException
★异常消息："现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。
★异常信息：   在 System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   在 System.Net.Sockets.Socket.ReceiveFromAsync(SocketAsyncEventArgs e)
   在 udp_csharp.UdpReceiveSocket.StartReceive() 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpReceiveSocket.cs:行号 66



程序出现异常
异常说明：System.Type--
2018-06-04 11:11:55
★异常类型：SocketException
★异常消息：通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
★异常信息：   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 udp_csharp.UdpReceiveSocket..ctor(String ip, Int32 sport, Int32 cport) 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpReceiveSocket.cs:行号 45



程序出现异常
异常说明：System.Type--
2018-06-04 11:11:59
★异常类型：NullReferenceException
★异常消息：未将对象引用设置到对象的实例。
★异常信息：   在 System.Net.Sockets.Socket.ReceiveFromAsync(SocketAsyncEventArgs e)
   在 udp_csharp.UdpReceiveSocket.StartReceive() 位置 f:\GitHub\CleanProcedure\CleanProcedure\UDP\UdpReceiveSocket.cs:行号 66



